<?php

return [
    'api_domain' => env('API_DOMAIN', 'https://ophim1.com/'),
    'image_domain' => env('IMAGE_DOMAIN', 'https://img.ophim9.cc/uploads/movies/'),
    'facebook_url' => env('APP_FACEBOOK_URL', 'https://www.facebook.com/example'),
    'countries' => [
        'trung-quoc' => 'Trung Quốc',
        'han-quoc' => 'Hàn Quốc',
        'nhat-ban' => 'Nhật Bản',
        'thai-lan' => 'Thái Lan',
        'au-my' => 'Âu Mỹ',
        'dai-loan' => 'Đài Loan',
        'hong-kong' => 'Hồng Kông',
        'an-do' => 'Ấn Độ',
        'anh' => 'Anh',
        'phap' => 'Pháp',
        'canada' => 'Canada',
        'quoc-gia-khac' => 'Quốc Nia Khác',
        'duc' => 'Đức',
        'tay-ban-nha' => 'Tây Ban Nha',
        'tho-nhi-ky' => 'Thổ Nhĩ Kỳ',
        'ha-lan' => 'Hà Lan',
        'indonesia' => 'Indonesia',
        'nga' => 'Nga',
        'mexico' => 'Mexico',
        'ba-lan' => 'Ba Lan',
        'uc' => 'Úc',
        'thuy-dien' => 'Thụy Điển',
        'malaysia' => 'Malaysia',
        'brazil' => 'Brazil',
        'philippines' => 'Philippines',
        'bo-dao-nha' => 'Bồ Đào Nha',
        'y' => 'Ý',
        'dan-mach' => 'Đan Mạch',
        'uae' => 'UAE',
        'na-uy' => 'Na Uy',
        'thuy-si' => 'Thụy Sĩ',
        'chau-phi' => 'Châu Phi',
        'nam-phi' => 'Nam Phi',
        'ukraina' => 'Ukraina',
        'arap-xe-ut' => 'Ả Rập Xê Út',
    ],
    'categories' => [
        'hanh-dong' => 'Hành Động',
        'tinh-cam' => 'Tình Cảm',
        'hai-huoc' => 'Hài Hước',
        'co-trang' => 'Cổ Trang',
        'tam-ly' => 'Tâm lý',
        'hinh-su' => 'Hình Sự',
        'chien-trang' => 'Chiến Trang',
        'the-thao' => 'Thể Thao',
        'vo-thuat' => 'Võ Thuật',
        'vien-tuong' => 'Viễn Tưởng',
        'phieu-luu' => 'Phiêu Lưu',
        'khoa-hoc' => 'Khoa Học',
        'kinh-di' => 'Kinh Dị',
        'am-nhac' => 'Âm Nhạc',
        'than-thoai' => 'Thần Thoại',
        'tai-lieu' => 'Tài Liệu',
        'gia-dinh' => 'Gia Đình',
        'chinh-kich' => 'Chính Kịch',
        'bi-an' => 'Bí Ẩn',
        'hoc-duong' => 'Học Đường',
        'kinh-dien' => 'Kinh Điển',
        'phim-18' => 'Phim 18+'
    ]
];
